version: 1
update_configs:
  - package_manager: "javascript"
    default_assignees:
      - "coemans"
    default_reviewers:
      - "coemans"
    directory: "/"
    update_schedule: "live"
  - package_manager: "docker"
    default_assignees:
      - "coemans"
    default_reviewers:
      - "coemans"
    directory: "/"
    update_schedule: "weekly"
